// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8WC9uGHFhmLp01yJ7M7jeYYHGjWvWwaQ',
    appId: '1:694259386258:web:750d304b94a1b8d4d0e34b',
    messagingSenderId: '694259386258',
    projectId: 'chatting-app-71f81',
    authDomain: 'chatting-app-71f81.firebaseapp.com',
    storageBucket: 'chatting-app-71f81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkPFqrd4IUnptU6UjXnA3dLkUEDMdw55I',
    appId: '1:694259386258:android:167649b227adf8a3d0e34b',
    messagingSenderId: '694259386258',
    projectId: 'chatting-app-71f81',
    storageBucket: 'chatting-app-71f81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZaGTHe4FSMxPgxnX5V9EXHIYqFgLNP_w',
    appId: '1:694259386258:ios:666f145ab16cd986d0e34b',
    messagingSenderId: '694259386258',
    projectId: 'chatting-app-71f81',
    storageBucket: 'chatting-app-71f81.appspot.com',
    iosClientId:
        '694259386258-sotlh2lj44n6tpp35e9p2rqkvv8027m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZaGTHe4FSMxPgxnX5V9EXHIYqFgLNP_w',
    appId: '1:694259386258:ios:666f145ab16cd986d0e34b',
    messagingSenderId: '694259386258',
    projectId: 'chatting-app-71f81',
    storageBucket: 'chatting-app-71f81.appspot.com',
    iosClientId:
        '694259386258-sotlh2lj44n6tpp35e9p2rqkvv8027m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
